# Generated by Django 4.2.4 on 2023-09-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Trade', models.CharField(max_length=255)),
                ('High', models.CharField(max_length=255)),
                ('Low', models.CharField(max_length=255)),
                ('Open', models.CharField(max_length=255)),
                ('Close', models.CharField(max_length=255)),
                ('Volume', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'stocklist',
            },
        ),
    ]
