# Generated by Django 4.2.4 on 2023-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='stock',
            name='Close',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='High',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Low',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Open',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Volume',
            field=models.IntegerField(max_length=255),
        ),
    ]
