# Generated by Django 4.2.4 on 2023-09-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_stock_options_alter_stock_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Volume',
            field=models.IntegerField(),
        ),
    ]
